### PR TITLE
Use compiled (single) regex rather than chain of ORs; add test data; accept more postcodes.

### PR DESCRIPTION
**Pull request by gimbo**
Hi there,

I came across this repo today, while looking for a regex that could match all ~2.5 million postcodes in [Doogal's postcode db](https://www.doogal.co.uk/UKPostcodes.php). This pull requests contains the following changes:
- I've rewritten `test_validation()` to read from a text file containing a sample of 10,000 postcodes from that DB. (Locally I tested it against it against the _full_ DB (almost - see next point), but I didn't include that file here because it's ~19MB.)
- I've tweaked the regexes to accept some postcodes it was previously rejecting. You _might_ want to reject this bit though, because I _think_ they're for defunct postcodes. Doogal's full DB includes NPT and GIR postcodes and I've removed them, but there were still some W1[A-Z] codes failing; I think they're defunct too but I wasn't sure and didn't want to check them all so I just expanded `thd` so they'd pass.
- Most substantially, I've entirely refactored `validation.py` so that:
  - The chain-of-ORs approach has been replaced with a single check of one big compound regex which is compiled upon module import.  (For testing the full 2.5 million rows, this resulted in about a 75% speedup, i.e. tests ran in a quarter of time than with the old version.)
  - The regex templates have been written using new string formatting so the interpolated bits are explicit. E.g. `'^[{fst}][1-9]\d[{inward}][{inward}]$'` instead of `'[%s][1-9]\d[%s][%s]$'`.
  - Since `is_valid_postcode` and `is_valid_partial_postcode` were, then, basically identical (apart from the regex they checked against), I've factored that logic out into a generic `_match_postcode` function and used `functools.partial` to declare them in terms of that.

I think that's it. I hope you'll find this useful.

Thanks!

-Andy

### CODE REVIEW

**Comment by dracos** [comment]
Thanks very much for this! :) You might as well remove that govtalk URL, it doesn't work any longer.

Would it be possible for you to split your changes into multiple atomic commits – ie. so the added test strings are one commit, the speed up rewrite another, the allowing through more strings a third.

On that last point, it looks like `thd` was missing P, but the other additions shouldn't be included, as W1M W1N W1R W1V W1X and W1Y were all removed in 2000.

**Comment by gimbo** [comment]
Excellent. Yep, I'll make those changes, and remove those errant W1\* postcodes from my test data.

**Comment by gimbo** [comment]
Haven't forgotten, just very busy. Might get to it this week, might not...

**Comment by dracos** [comment]
Hi, I have merged this to our master, split up into two commits. Thanks again for this :)

**Pull request closed without merging**
